config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:index, :show, :destroy]
  resources :scrapes, except: [:edit, :new]
  
  root :to => 'scrapes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :scrape

    def to_s
        self.image_url
    end
end

app/models/scrape.rb
class Scrape < ApplicationRecord
    enum status: [:complete, :incomplete]

    validates :url, presence: true

    has_many :images, dependent: :destroy

    def largest_image
        max_image_size = self.images.maximum('size')
        self.images.where(size: max_image_size).first
    end

    def to_s
        self.url
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end
 
  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image_url, :size)
    end
end

app/controllers/scrapes_controller.rb
class ScrapesController < ApplicationController
  before_action :set_scrape, only: [:show, :edit, :update, :destroy]

  # GET /scrapes
  # GET /scrapes.json
  def index
    @scrapes = Scrape.all
    @scrape = Scrape.new
  end

  # GET /scrapes/1
  # GET /scrapes/1.json
  def show
  end

  # GET /scrapes/new
  def new
    @scrape = Scrape.new
  end

  # GET /scrapes/1/edit
  def edit
  end

  # POST /scrapes
  # POST /scrapes.json
  def create
    @scrape = Scrape.new(scrape_params)
    @scrape.status = :incomplete

    respond_to do |format|
      if @scrape.save
        format.html { redirect_to scrapes_path, notice: 'Created scrape. Images are being scraped...' }
        format.json { render :show, status: :created, location: @scrape }

        ScrapeLargestImageJob.perform_later @scrape
      else
        format.html { render :new }
        format.json { render json: @scrape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrapes/1
  # PATCH/PUT /scrapes/1.json
  def update
    respond_to do |format|
      if @scrape.update(scrape_params)
        format.html { redirect_to @scrape, notice: 'Scrape was successfully updated.' }
        format.json { render :show, status: :ok, location: @scrape }
      else
        format.html { render :edit }
        format.json { render json: @scrape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrapes/1
  # DELETE /scrapes/1.json
  def destroy
    @scrape.destroy
    respond_to do |format|
      format.html { redirect_to scrapes_url, notice: 'Scrape was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrape
      @scrape = Scrape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrape_params
      params.require(:scrape).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/scrapes_helper.rb
module ScrapesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Images (<%= @images.count %>)</h2>

<br>

<table class="table">
  <thead>
    <tr>
      <th>Image url</th>
      <th>Scrape</th>
      <th>Size</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image_url %></td>
        <td><%= image.scrape %></td>
        <td><%= image.size %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Image from <%= @image.scrape %></h2>

<br>

<a href="<%= @image.image_url %>"><%= @image.image_url %></a>

<br><br>

<img src="<%= @image.image_url %>">

<br>

<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul style="text-align: center">
      <li style="display: inline; margin-right: 30px"><a href="<%= scrapes_path %>">Scrapes</a></li>
      <li style="display: inline"><a href="<%= images_path %>">Images</a></li>
    </ul>  
    <%= yield %>
  </body>
</html>

app/views/scrapes/_form.html.erb
<%= form_with(model: scrape, local: true) do |form| %>
  <% if scrape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scrape.errors.count, "error") %> prohibited this scrape from being saved:</h2>

      <ul>
      <% scrape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :largest_image %>
    <%= form.text_field :largest_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scrapes/edit.html.erb
<h1>Editing Scrape</h1>

<%= render 'form', scrape: @scrape %>

<%= link_to 'Show', @scrape %> |
<%= link_to 'Back', scrapes_path %>

app/views/scrapes/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h3>Scrapes</h3>

<br>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Created At</th>
      <th>Status</th>
      <th># Images</th>
      <th>Largest image</th>
      <th>Show</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @scrapes.each do |scrape| %>
      <tr>
        <td><%= scrape.url %></td>
        <td><%= scrape.created_at %></td>
        <td><%= scrape.status %></td>
        <td><%= scrape.images.count %></td>
        <td><%= scrape.largest_image %></td>
        <td><%= link_to 'Show', scrape %></td>
        <td><%= link_to 'Destroy', scrape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h5>New Scrape</h5>

<%= form_with(model: @scrape, local: true) do |form| %>
  <% if @scrape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scrape.errors.count, "error") %> prohibited this scrape from being saved:</h2>

      <ul>
      <% @scrape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url, "URL" %>
    <br>
    <%= form.text_field :url, placeholder: "https://nfl.com" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scrapes/new.html.erb
<h2>New Scrape</h2>

<%= form_with(model: @scrape, local: true) do |form| %>
  <% if @scrape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scrape.errors.count, "error") %> prohibited this scrape from being saved:</h2>

      <ul>
      <% @scrape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <br>
    <%= form.text_field :url, placeholder: "https://nfl.com" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>

<%= link_to 'Back', scrapes_path %>

app/views/scrapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @scrape.url %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @scrape.created_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @scrape.status %>
</p>

<p>
  <strong>Largest image:</strong>
  <%= @scrape.largest_image %>
</p>

<%= link_to 'Back', scrapes_path %>